# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bee7031fc6e67c6445ad2a2d920885eeeb47e0933b7eeaf544fae01e462cc90da5b3ca12d9588e92624ac14be9c9520511ca4e20737c130ba60cc41a3b06d7fb

test:
  secret_key_base: 3a176c503c5031f206b4af377e7d145147ebcf63de3ac3a7fc42cd58532a6dcffdc924f949f2c0351ec175c02ba57f735694cad108d4a74f9432500c0f29e914

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
